// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjV8gg1cOc7JLvzEcWw6xyxps8J8MvGc',
    appId: '1:9073520357:web:cd5e62475bb1e9b785ee0c',
    messagingSenderId: '9073520357',
    projectId: 'vitalex-d8c34',
    authDomain: 'vitalex-d8c34.firebaseapp.com',
    storageBucket: 'vitalex-d8c34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARcWIT4-pnOVWjLVEFHiTS9dpHiFIYTwM',
    appId: '1:9073520357:android:6bb9341aba3bd80185ee0c',
    messagingSenderId: '9073520357',
    projectId: 'vitalex-d8c34',
    storageBucket: 'vitalex-d8c34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPTZJ4qX6_UyC1oLj2aUBMzXkLQ8eYeEQ',
    appId: '1:9073520357:ios:18e502f8155e1ecb85ee0c',
    messagingSenderId: '9073520357',
    projectId: 'vitalex-d8c34',
    storageBucket: 'vitalex-d8c34.firebasestorage.app',
    iosBundleId: 'com.example.vitalex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPTZJ4qX6_UyC1oLj2aUBMzXkLQ8eYeEQ',
    appId: '1:9073520357:ios:18e502f8155e1ecb85ee0c',
    messagingSenderId: '9073520357',
    projectId: 'vitalex-d8c34',
    storageBucket: 'vitalex-d8c34.firebasestorage.app',
    iosBundleId: 'com.example.vitalex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvjV8gg1cOc7JLvzEcWw6xyxps8J8MvGc',
    appId: '1:9073520357:web:11930e7029e86eea85ee0c',
    messagingSenderId: '9073520357',
    projectId: 'vitalex-d8c34',
    authDomain: 'vitalex-d8c34.firebaseapp.com',
    storageBucket: 'vitalex-d8c34.firebasestorage.app',
  );
}
